<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (RATION?,MENU?,ITEMTYPE?,ITEM?,WEIGHT?,CALORIES?,TOTALFAT_G?,TOTALFAT_DV?,SATURATEDFAT_G?,SATURATEDFAT_DV?,TRANSFAT_G?,CHOLESTEROL_MG?,CHOLESTEROL_DV?,SODIUM_MG?,SODIUM_DV?,POTASSIUM_MG?,CARBOHYDRATES_G?,CARBOHYDRATES_DV?,DIETARYFIBER_G?,DIETARYFIBER_DV?,SUGARS_G?,PROTEIN_G?,VITAMINA_IU?,VITAMINA_DV?,VITAMINC_MG?,VITAMINC_DV?,CALCIUM_MG?,CALCIUM_DV?,IRON_MG?,IRON_DV?,VITAMIND_MCG?,VITAMINE_MG?,VITAMINK_MCG?,THIAMIN_MG?,RIBOFLAVIN_MG?,NIACIN_MG?,VITAMINB6_MG?,FOLICACID_MCG?,VITAMINB12_MCG?,PHOSPHOROUS_MG?,IODINE_MCG?,MAGNESIUM_MG?,ZINC_MG?,SELENIUM_MCG?)+>
  <!ELEMENT RATION (#PCDATA)>
  <!ELEMENT MENU (#PCDATA)>
  <!ELEMENT ITEMTYPE (#PCDATA)>
  <!ELEMENT ITEM (#PCDATA)>
  <!ELEMENT WEIGHT (#PCDATA)>
  <!ELEMENT CALORIES (#PCDATA)>
  <!ELEMENT TOTALFAT_G (#PCDATA)>
  <!ELEMENT TOTALFAT_DV (#PCDATA)>
  <!ELEMENT SATURATEDFAT_G (#PCDATA)>
  <!ELEMENT SATURATEDFAT_DV (#PCDATA)>
  <!ELEMENT TRANSFAT_G (#PCDATA)>
  <!ELEMENT CHOLESTEROL_MG (#PCDATA)>
  <!ELEMENT CHOLESTEROL_DV (#PCDATA)>
  <!ELEMENT SODIUM_MG (#PCDATA)>
  <!ELEMENT SODIUM_DV (#PCDATA)>
  <!ELEMENT POTASSIUM_MG (#PCDATA)>
  <!ELEMENT CARBOHYDRATES_G (#PCDATA)>
  <!ELEMENT CARBOHYDRATES_DV (#PCDATA)>
  <!ELEMENT DIETARYFIBER_G (#PCDATA)>
  <!ELEMENT DIETARYFIBER_DV (#PCDATA)>
  <!ELEMENT SUGARS_G (#PCDATA)>
  <!ELEMENT PROTEIN_G (#PCDATA)>
  <!ELEMENT VITAMINA_IU (#PCDATA)>
  <!ELEMENT VITAMINA_DV (#PCDATA)>
  <!ELEMENT VITAMINC_MG (#PCDATA)>
  <!ELEMENT VITAMINC_DV (#PCDATA)>
  <!ELEMENT CALCIUM_MG (#PCDATA)>
  <!ELEMENT CALCIUM_DV (#PCDATA)>
  <!ELEMENT IRON_MG (#PCDATA)>
  <!ELEMENT IRON_DV (#PCDATA)>
  <!ELEMENT VITAMIND_MCG (#PCDATA)>
  <!ELEMENT VITAMINE_MG (#PCDATA)>
  <!ELEMENT VITAMINK_MCG (#PCDATA)>
  <!ELEMENT THIAMIN_MG (#PCDATA)>
  <!ELEMENT RIBOFLAVIN_MG (#PCDATA)>
  <!ELEMENT NIACIN_MG (#PCDATA)>
  <!ELEMENT VITAMINB6_MG (#PCDATA)>
  <!ELEMENT FOLICACID_MCG (#PCDATA)>
  <!ELEMENT VITAMINB12_MCG (#PCDATA)>
  <!ELEMENT PHOSPHOROUS_MG (#PCDATA)>
  <!ELEMENT IODINE_MCG (#PCDATA)>
  <!ELEMENT MAGNESIUM_MG (#PCDATA)>
  <!ELEMENT ZINC_MG (#PCDATA)>
  <!ELEMENT SELENIUM_MCG (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Entree</ITEMTYPE>
    <ITEM>Sandwich, Shelf Stable, Bacon Cheddar</ITEM>
    <WEIGHT>88</WEIGHT>
    <CALORIES>327.36</CALORIES>
    <TOTALFAT_G>14.52</TOTALFAT_G>
    <TOTALFAT_DV>.22&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>4.95</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.25&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>2.13</TRANSFAT_G>
    <CHOLESTEROL_MG>20</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>687.28</SODIUM_MG>
    <SODIUM_DV>.29&#37;</SODIUM_DV>
    <POTASSIUM_MG>177.76</POTASSIUM_MG>
    <CARBOHYDRATES_G>37.31</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.12&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.86</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.07&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>12.14</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.88</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>68.99</CALCIUM_MG>
    <CALCIUM_DV>.07&#37;</CALCIUM_DV>
    <IRON_MG>2.24</IRON_MG>
    <IRON_DV>.12&#37;</IRON_DV>
    <VITAMINE_MG>.5</VITAMINE_MG>
    <THIAMIN_MG>.29</THIAMIN_MG>
    <RIBOFLAVIN_MG>.33</RIBOFLAVIN_MG>
    <NIACIN_MG>5.27</NIACIN_MG>
    <VITAMINB6_MG>.12</VITAMINB6_MG>
    <FOLICACID_MCG>82.37</FOLICACID_MCG>
    <VITAMINB12_MCG>.18</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>129.36</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>23.23</MAGNESIUM_MG>
    <ZINC_MG>1.37</ZINC_MG>
    <SELENIUM_MCG>18.74</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Entree</ITEMTYPE>
    <ITEM>Sandwich, Shelf Stable, Pepperoni</ITEM>
    <WEIGHT>70</WEIGHT>
    <CALORIES>265.3</CALORIES>
    <TOTALFAT_G>14.63</TOTALFAT_G>
    <TOTALFAT_DV>.23&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>4.84</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.24&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.32</TRANSFAT_G>
    <CHOLESTEROL_MG>20</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>571.9</SODIUM_MG>
    <SODIUM_DV>.24&#37;</SODIUM_DV>
    <POTASSIUM_MG>135.1</POTASSIUM_MG>
    <CARBOHYDRATES_G>25.27</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.08&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.18</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.05&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>9.66</PROTEIN_G>
    <VITAMINA_IU>128.3</VITAMINA_IU>
    <VITAMINA_DV>.03&#37;</VITAMINA_DV>
    <VITAMINC_MG>.7</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>47.95</CALCIUM_MG>
    <CALCIUM_DV>.05&#37;</CALCIUM_DV>
    <IRON_MG>1.42</IRON_MG>
    <IRON_DV>.08&#37;</IRON_DV>
    <VITAMINE_MG>.49</VITAMINE_MG>
    <THIAMIN_MG>.19</THIAMIN_MG>
    <RIBOFLAVIN_MG>.21</RIBOFLAVIN_MG>
    <NIACIN_MG>3.12</NIACIN_MG>
    <VITAMINB6_MG>.11</VITAMINB6_MG>
    <FOLICACID_MCG>48.93</FOLICACID_MCG>
    <VITAMINB12_MCG>.25</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>91</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>17.08</MAGNESIUM_MG>
    <ZINC_MG>1.13</ZINC_MG>
    <SELENIUM_MCG>16.66</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Beef Snacks, Barbecue</ITEM>
    <WEIGHT>26</WEIGHT>
    <CALORIES>76.7</CALORIES>
    <TOTALFAT_G>2.78</TOTALFAT_G>
    <TOTALFAT_DV>.04&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.17</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.06&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.13</TRANSFAT_G>
    <CHOLESTEROL_MG>20</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>564.2</SODIUM_MG>
    <SODIUM_DV>.24&#37;</SODIUM_DV>
    <POTASSIUM_MG>173.94</POTASSIUM_MG>
    <CARBOHYDRATES_G>4.91</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.02&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.72</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.03&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>8.61</PROTEIN_G>
    <VITAMINA_IU>131.2</VITAMINA_IU>
    <VITAMINA_DV>.03&#37;</VITAMINA_DV>
    <VITAMINC_MG>.26</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>13.7</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>1.16</IRON_MG>
    <IRON_DV>.06&#37;</IRON_DV>
    <VITAMINE_MG>.33</VITAMINE_MG>
    <THIAMIN_MG>.03</THIAMIN_MG>
    <RIBOFLAVIN_MG>.15</RIBOFLAVIN_MG>
    <NIACIN_MG>1.38</NIACIN_MG>
    <VITAMINB6_MG>.05</VITAMINB6_MG>
    <FOLICACID_MCG>5.36</FOLICACID_MCG>
    <VITAMINB12_MCG>1.53</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>73.06</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>12.4</MAGNESIUM_MG>
    <ZINC_MG>1.29</ZINC_MG>
    <SELENIUM_MCG>6.37</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Nut and Fruit Mix, Sunflower Kernels and Infused Fruit</ITEM>
    <WEIGHT>56</WEIGHT>
    <CALORIES>314.72</CALORIES>
    <TOTALFAT_G>21.17</TOTALFAT_G>
    <TOTALFAT_DV>.33&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.18</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.16&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.03</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>5.6</SODIUM_MG>
    <SODIUM_DV>0&#37;</SODIUM_DV>
    <POTASSIUM_MG>339.92</POTASSIUM_MG>
    <CARBOHYDRATES_G>18.42</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.06&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>10.58</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.42&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>12.6</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.56</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>43.12</CALCIUM_MG>
    <CALCIUM_DV>.04&#37;</CALCIUM_DV>
    <IRON_MG>1.07</IRON_MG>
    <IRON_DV>.06&#37;</IRON_DV>
    <VITAMINE_MG>3.65</VITAMINE_MG>
    <THIAMIN_MG>.08</THIAMIN_MG>
    <RIBOFLAVIN_MG>.09</RIBOFLAVIN_MG>
    <NIACIN_MG>5.88</NIACIN_MG>
    <VITAMINB6_MG>.31</VITAMINB6_MG>
    <FOLICACID_MCG>47.66</FOLICACID_MCG>
    <VITAMINB12_MCG>.07</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>190.96</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>91.84</MAGNESIUM_MG>
    <ZINC_MG>1.57</ZINC_MG>
    <SELENIUM_MCG>4.65</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Beef Snacks, Teriyaki</ITEM>
    <WEIGHT>26</WEIGHT>
    <CALORIES>78.26</CALORIES>
    <TOTALFAT_G>2.94</TOTALFAT_G>
    <TOTALFAT_DV>.05&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.33</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.07&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.13</TRANSFAT_G>
    <CHOLESTEROL_MG>20</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>608.4</SODIUM_MG>
    <SODIUM_DV>.25&#37;</SODIUM_DV>
    <POTASSIUM_MG>167.44</POTASSIUM_MG>
    <CARBOHYDRATES_G>5.51</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.02&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.54</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.02&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>7.8</PROTEIN_G>
    <VITAMINA_IU>26.9</VITAMINA_IU>
    <VITAMINA_DV>.01&#37;</VITAMINA_DV>
    <VITAMINC_MG>.26</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>15.21</CALCIUM_MG>
    <CALCIUM_DV>.02&#37;</CALCIUM_DV>
    <IRON_MG>1.23</IRON_MG>
    <IRON_DV>.07&#37;</IRON_DV>
    <VITAMINE_MG>.26</VITAMINE_MG>
    <THIAMIN_MG>.03</THIAMIN_MG>
    <RIBOFLAVIN_MG>.15</RIBOFLAVIN_MG>
    <NIACIN_MG>1.37</NIACIN_MG>
    <VITAMINB6_MG>.06</VITAMINB6_MG>
    <FOLICACID_MCG>5.82</FOLICACID_MCG>
    <VITAMINB12_MCG>1.54</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>72.28</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>12.58</MAGNESIUM_MG>
    <ZINC_MG>1.31</ZINC_MG>
    <SELENIUM_MCG>6.94</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Filled Bakery, Filled French Toast</ITEM>
    <WEIGHT>99</WEIGHT>
    <CALORIES>322.74</CALORIES>
    <TOTALFAT_G>10.1</TOTALFAT_G>
    <TOTALFAT_DV>.16&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.55</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.18&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.83</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>305.91</SODIUM_MG>
    <SODIUM_DV>.13&#37;</SODIUM_DV>
    <POTASSIUM_MG>76.13</POTASSIUM_MG>
    <CARBOHYDRATES_G>52.27</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.17&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>2</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.08&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>6.83</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.99</VITAMINC_MG>
    <VITAMINC_DV>.02&#37;</VITAMINC_DV>
    <CALCIUM_MG>60.89</CALCIUM_MG>
    <CALCIUM_DV>.06&#37;</CALCIUM_DV>
    <IRON_MG>2.53</IRON_MG>
    <IRON_DV>.14&#37;</IRON_DV>
    <VITAMIND_MCG>0</VITAMIND_MCG>
    <VITAMINE_MG>.62</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.27</THIAMIN_MG>
    <RIBOFLAVIN_MG>.28</RIBOFLAVIN_MG>
    <NIACIN_MG>2.83</NIACIN_MG>
    <VITAMINB6_MG>.06</VITAMINB6_MG>
    <FOLICACID_MCG>67.72</FOLICACID_MCG>
    <VITAMINB12_MCG>.12</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>58.91</PHOSPHOROUS_MG>
    <IODINE_MCG>.85</IODINE_MCG>
    <MAGNESIUM_MG>16.04</MAGNESIUM_MG>
    <ZINC_MG>.7</ZINC_MG>
    <SELENIUM_MCG>16.14</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Dessert Bar, Peanut Butter</ITEM>
    <WEIGHT>40</WEIGHT>
    <CALORIES>231.6</CALORIES>
    <TOTALFAT_G>17.16</TOTALFAT_G>
    <TOTALFAT_DV>.26&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>6.08</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.3&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.47</TRANSFAT_G>
    <CHOLESTEROL_MG>20.24</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>37.08</SODIUM_MG>
    <SODIUM_DV>.02&#37;</SODIUM_DV>
    <POTASSIUM_MG>242.8</POTASSIUM_MG>
    <CARBOHYDRATES_G>16.12</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.05&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>8.52</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.34&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>6.76</PROTEIN_G>
    <VITAMINA_IU>185.9</VITAMINA_IU>
    <VITAMINA_DV>.04&#37;</VITAMINA_DV>
    <VITAMINC_MG>.4</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>77.6</CALCIUM_MG>
    <CALCIUM_DV>.08&#37;</CALCIUM_DV>
    <IRON_MG>.22</IRON_MG>
    <IRON_DV>.01&#37;</IRON_DV>
    <VITAMIND_MCG>.3</VITAMIND_MCG>
    <VITAMINE_MG>1.62</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.02</THIAMIN_MG>
    <RIBOFLAVIN_MG>.16</RIBOFLAVIN_MG>
    <NIACIN_MG>2.59</NIACIN_MG>
    <VITAMINB6_MG>.05</VITAMINB6_MG>
    <FOLICACID_MCG>13.16</FOLICACID_MCG>
    <VITAMINB12_MCG>.22</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>138.8</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>31.76</MAGNESIUM_MG>
    <ZINC_MG>.75</ZINC_MG>
    <SELENIUM_MCG>3.08</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>First Strike Bar, Mini, Mocha</ITEM>
    <WEIGHT>35</WEIGHT>
    <CALORIES>150.15</CALORIES>
    <TOTALFAT_G>5.06</TOTALFAT_G>
    <TOTALFAT_DV>.08&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.99</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.1&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.81</TRANSFAT_G>
    <CHOLESTEROL_MG>5.34</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.02&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>26.2</SODIUM_MG>
    <SODIUM_DV>.01&#37;</SODIUM_DV>
    <POTASSIUM_MG>81.03</POTASSIUM_MG>
    <CARBOHYDRATES_G>24.94</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.08&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.67</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.07&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>1.72</PROTEIN_G>
    <VITAMINA_IU>9.15</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>8.12</VITAMINC_MG>
    <VITAMINC_DV>.14&#37;</VITAMINC_DV>
    <CALCIUM_MG>21</CALCIUM_MG>
    <CALCIUM_DV>.02&#37;</CALCIUM_DV>
    <IRON_MG>.75</IRON_MG>
    <IRON_DV>.04&#37;</IRON_DV>
    <VITAMIND_MCG>.8</VITAMIND_MCG>
    <VITAMINE_MG>7.17</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.25</THIAMIN_MG>
    <RIBOFLAVIN_MG>.41</RIBOFLAVIN_MG>
    <NIACIN_MG>4.01</NIACIN_MG>
    <VITAMINB6_MG>.45</VITAMINB6_MG>
    <FOLICACID_MCG>103.95</FOLICACID_MCG>
    <VITAMINB12_MCG>.83</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>36.75</PHOSPHOROUS_MG>
    <IODINE_MCG>0</IODINE_MCG>
    <MAGNESIUM_MG>15.26</MAGNESIUM_MG>
    <ZINC_MG>1.72</ZINC_MG>
    <SELENIUM_MCG>1.17</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>First Strike Bar, Mini, Chocolate</ITEM>
    <WEIGHT>35</WEIGHT>
    <CALORIES>149.8</CALORIES>
    <TOTALFAT_G>5.08</TOTALFAT_G>
    <TOTALFAT_DV>.08&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.66</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.08&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.01</TRANSFAT_G>
    <CHOLESTEROL_MG>2.67</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.01&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>18.1</SODIUM_MG>
    <SODIUM_DV>.01&#37;</SODIUM_DV>
    <POTASSIUM_MG>111.3</POTASSIUM_MG>
    <CARBOHYDRATES_G>24.26</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.08&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.26</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.05&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>2.03</PROTEIN_G>
    <VITAMINA_IU>43.9</VITAMINA_IU>
    <VITAMINA_DV>.01&#37;</VITAMINA_DV>
    <VITAMINC_MG>13.16</VITAMINC_MG>
    <VITAMINC_DV>.22&#37;</VITAMINC_DV>
    <CALCIUM_MG>21.39</CALCIUM_MG>
    <CALCIUM_DV>.02&#37;</CALCIUM_DV>
    <IRON_MG>1.7</IRON_MG>
    <IRON_DV>.09&#37;</IRON_DV>
    <VITAMIND_MCG>1.1</VITAMIND_MCG>
    <VITAMINE_MG>8.56</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.27</THIAMIN_MG>
    <RIBOFLAVIN_MG>.32</RIBOFLAVIN_MG>
    <NIACIN_MG>2.98</NIACIN_MG>
    <VITAMINB6_MG>.31</VITAMINB6_MG>
    <FOLICACID_MCG>135.8</FOLICACID_MCG>
    <VITAMINB12_MCG>1.02</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>13.39</PHOSPHOROUS_MG>
    <IODINE_MCG>0</IODINE_MCG>
    <MAGNESIUM_MG>21.56</MAGNESIUM_MG>
    <ZINC_MG>1.83</ZINC_MG>
    <SELENIUM_MCG>1.05</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Bread/Crax</ITEMTYPE>
    <ITEM>Snack Bread, Wheat</ITEM>
    <WEIGHT>57</WEIGHT>
    <CALORIES>201.78</CALORIES>
    <TOTALFAT_G>6.21</TOTALFAT_G>
    <TOTALFAT_DV>.1&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.53</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.08&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.57</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>369.36</SODIUM_MG>
    <SODIUM_DV>.15&#37;</SODIUM_DV>
    <POTASSIUM_MG>80.94</POTASSIUM_MG>
    <CARBOHYDRATES_G>32.43</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.11&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.82</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.07&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>4.73</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.57</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>172.71</CALCIUM_MG>
    <CALCIUM_DV>.17&#37;</CALCIUM_DV>
    <IRON_MG>1.98</IRON_MG>
    <IRON_DV>.11&#37;</IRON_DV>
    <VITAMIND_MCG>0</VITAMIND_MCG>
    <VITAMINE_MG>.26</VITAMINE_MG>
    <THIAMIN_MG>.25</THIAMIN_MG>
    <RIBOFLAVIN_MG>.2</RIBOFLAVIN_MG>
    <NIACIN_MG>2.6</NIACIN_MG>
    <VITAMINB6_MG>.05</VITAMINB6_MG>
    <FOLICACID_MCG>58.14</FOLICACID_MCG>
    <VITAMINB12_MCG>.07</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>148.2</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>18.87</MAGNESIUM_MG>
    <ZINC_MG>.43</ZINC_MG>
    <SELENIUM_MCG>19.67</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Spread</ITEMTYPE>
    <ITEM>Cheese Spread, Cheddar with Jalapeno Peppers</ITEM>
    <WEIGHT>42.5</WEIGHT>
    <CALORIES>162.78</CALORIES>
    <TOTALFAT_G>16.32</TOTALFAT_G>
    <TOTALFAT_DV>.25&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>8.84</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.44&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.8</TRANSFAT_G>
    <CHOLESTEROL_MG>24.43</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.08&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>603.5</SODIUM_MG>
    <SODIUM_DV>.25&#37;</SODIUM_DV>
    <POTASSIUM_MG>27.29</POTASSIUM_MG>
    <CARBOHYDRATES_G>3.4</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.43</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.02&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>5.19</PROTEIN_G>
    <VITAMINA_IU>2675.5</VITAMINA_IU>
    <VITAMINA_DV>.54&#37;</VITAMINA_DV>
    <VITAMINC_MG>19.55</VITAMINC_MG>
    <VITAMINC_DV>.33&#37;</VITAMINC_DV>
    <CALCIUM_MG>155.13</CALCIUM_MG>
    <CALCIUM_DV>.16&#37;</CALCIUM_DV>
    <IRON_MG>.09</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <VITAMIND_MCG>0</VITAMIND_MCG>
    <VITAMINE_MG>1.3</VITAMINE_MG>
    <THIAMIN_MG>.41</THIAMIN_MG>
    <RIBOFLAVIN_MG>.12</RIBOFLAVIN_MG>
    <NIACIN_MG>.04</NIACIN_MG>
    <VITAMINB6_MG>.82</VITAMINB6_MG>
    <FOLICACID_MCG>2.55</FOLICACID_MCG>
    <VITAMINB12_MCG>.09</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>263.5</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>6.25</MAGNESIUM_MG>
    <ZINC_MG>.87</ZINC_MG>
    <SELENIUM_MCG>6.46</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Candy</ITEMTYPE>
    <ITEM>Caffeinated Gum, Cinnamon</ITEM>
    <WEIGHT>12.5</WEIGHT>
    <CALORIES>50</CALORIES>
    <CARBOHYDRATES_G>10</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.03&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
    <VITAMINA_DV> </VITAMINA_DV>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Condiment</ITEMTYPE>
    <ITEM>Hot Sauce, Extra Hot 4x</ITEM>
    <WEIGHT>4</WEIGHT>
    <CALORIES>0</CALORIES>
    <TOTALFAT_G>.02</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>22.6</SODIUM_MG>
    <SODIUM_DV>.01&#37;</SODIUM_DV>
    <POTASSIUM_MG>4.12</POTASSIUM_MG>
    <CARBOHYDRATES_G>.04</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>0&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.03</PROTEIN_G>
    <VITAMINA_DV> </VITAMINA_DV>
    <VITAMINC_MG>0</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>.6</CALCIUM_MG>
    <CALCIUM_DV>0&#37;</CALCIUM_DV>
    <IRON_MG>.06</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <VITAMINE_MG>0</VITAMINE_MG>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>0</RIBOFLAVIN_MG>
    <NIACIN_MG>.01</NIACIN_MG>
    <VITAMINB6_MG>.01</VITAMINB6_MG>
    <FOLICACID_MCG>0</FOLICACID_MCG>
    <VITAMINB12_MCG>0</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>.68</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>.4</MAGNESIUM_MG>
    <ZINC_MG>0</ZINC_MG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Beverage</ITEMTYPE>
    <ITEM>Beverage Base, Ergo, Formulation E</ITEM>
    <WEIGHT>47</WEIGHT>
    <CALORIES>171.08</CALORIES>
    <TOTALFAT_G>.05</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>0</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>0</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>87.89</SODIUM_MG>
    <SODIUM_DV>.04&#37;</SODIUM_DV>
    <POTASSIUM_MG>4.7</POTASSIUM_MG>
    <CARBOHYDRATES_G>42.54</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.14&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.47</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.02&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.28</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>37.08</VITAMINC_MG>
    <VITAMINC_DV>.62&#37;</VITAMINC_DV>
    <CALCIUM_MG>6.82</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>.12</IRON_MG>
    <IRON_DV>.01&#37;</IRON_DV>
    <VITAMINE_MG>.21</VITAMINE_MG>
    <THIAMIN_MG>.01</THIAMIN_MG>
    <RIBOFLAVIN_MG>.01</RIBOFLAVIN_MG>
    <NIACIN_MG>.01</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>2.82</FOLICACID_MCG>
    <VITAMINB12_MCG>.06</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>2.87</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>2.39</MAGNESIUM_MG>
    <ZINC_MG>.04</ZINC_MG>
    <SELENIUM_MCG>1.41</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Beverage</ITEMTYPE>
    <ITEM>Beverage Base, Ergo, Formulation E</ITEM>
    <WEIGHT>47</WEIGHT>
    <CALORIES>171.08</CALORIES>
    <TOTALFAT_G>.05</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>0</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>0</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>87.89</SODIUM_MG>
    <SODIUM_DV>.04&#37;</SODIUM_DV>
    <POTASSIUM_MG>4.7</POTASSIUM_MG>
    <CARBOHYDRATES_G>42.54</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.14&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.47</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.02&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.28</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>37.08</VITAMINC_MG>
    <VITAMINC_DV>.62&#37;</VITAMINC_DV>
    <CALCIUM_MG>6.82</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>.12</IRON_MG>
    <IRON_DV>.01&#37;</IRON_DV>
    <VITAMINE_MG>.21</VITAMINE_MG>
    <THIAMIN_MG>.01</THIAMIN_MG>
    <RIBOFLAVIN_MG>.01</RIBOFLAVIN_MG>
    <NIACIN_MG>.01</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>2.82</FOLICACID_MCG>
    <VITAMINB12_MCG>.06</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>2.87</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>2.39</MAGNESIUM_MG>
    <ZINC_MG>.04</ZINC_MG>
    <SELENIUM_MCG>1.41</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Fruit</ITEMTYPE>
    <ITEM>Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced</ITEM>
    <WEIGHT>128</WEIGHT>
    <CALORIES>143.36</CALORIES>
    <TOTALFAT_G>.13</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>.01</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.01</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>15.23</SODIUM_MG>
    <SODIUM_DV>.01&#37;</SODIUM_DV>
    <POTASSIUM_MG>84.61</POTASSIUM_MG>
    <CARBOHYDRATES_G>35.58</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.12&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.56</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.06&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.26</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>244.48</VITAMINC_MG>
    <VITAMINC_DV>4.07&#37;</VITAMINC_DV>
    <CALCIUM_MG>6.37</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>.16</IRON_MG>
    <IRON_DV>.01&#37;</IRON_DV>
    <VITAMINE_MG>.58</VITAMINE_MG>
    <VITAMINK_MCG>4.59</VITAMINK_MCG>
    <THIAMIN_MG>.04</THIAMIN_MG>
    <RIBOFLAVIN_MG>.03</RIBOFLAVIN_MG>
    <NIACIN_MG>.08</NIACIN_MG>
    <VITAMINB6_MG>.06</VITAMINB6_MG>
    <FOLICACID_MCG>7.68</FOLICACID_MCG>
    <VITAMINB12_MCG>.15</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>10.14</PHOSPHOROUS_MG>
    <IODINE_MCG>0</IODINE_MCG>
    <MAGNESIUM_MG>4.01</MAGNESIUM_MG>
    <ZINC_MG>.07</ZINC_MG>
    <SELENIUM_MCG>3.84</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>FSR 2008 Accessory Packet C </ITEMTYPE>
    <ITEM>Apple Cider, Spiced</ITEM>
    <WEIGHT>17</WEIGHT>
    <CALORIES>67.66</CALORIES>
    <TOTALFAT_G>.07</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>.02</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>0</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>22.95</SODIUM_MG>
    <SODIUM_DV>.01&#37;</SODIUM_DV>
    <POTASSIUM_MG>1.7</POTASSIUM_MG>
    <CARBOHYDRATES_G>16.81</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.06&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.17</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.01&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.07</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>39.1</VITAMINC_MG>
    <VITAMINC_DV>.65&#37;</VITAMINC_DV>
    <CALCIUM_MG>13.18</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>.03</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <VITAMIND_MCG>0</VITAMIND_MCG>
    <VITAMINE_MG>.08</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>0</RIBOFLAVIN_MG>
    <NIACIN_MG>.01</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>1.02</FOLICACID_MCG>
    <VITAMINB12_MCG>.02</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>4.32</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>.36</MAGNESIUM_MG>
    <ZINC_MG>.01</ZINC_MG>
    <SELENIUM_MCG>.51</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>FSR 2008 Accessory Packet C </ITEMTYPE>
    <ITEM>Chewing Gum, Xylitol</ITEM>
    <WEIGHT>3.2</WEIGHT>
    <CARBOHYDRATES_G>2</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>FSR 2008 Accessory Packet C </ITEMTYPE>
    <ITEM>Salt, Iodized</ITEM>
    <WEIGHT>4</WEIGHT>
    <CALORIES>0</CALORIES>
    <TOTALFAT_G>0</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>0</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>1550.32</SODIUM_MG>
    <SODIUM_DV>.65&#37;</SODIUM_DV>
    <POTASSIUM_MG>.32</POTASSIUM_MG>
    <CARBOHYDRATES_G>0</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>0&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>0</DIETARYFIBER_G>
    <DIETARYFIBER_DV>0&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>0</PROTEIN_G>
    <VITAMINC_MG>0</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>0</CALCIUM_MG>
    <CALCIUM_DV>0&#37;</CALCIUM_DV>
    <IRON_MG>.01</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
    <THIAMIN_MG>0</THIAMIN_MG>
    <RIBOFLAVIN_MG>0</RIBOFLAVIN_MG>
    <NIACIN_MG>0</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>0</FOLICACID_MCG>
    <VITAMINB12_MCG>0</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>0</PHOSPHOROUS_MG>
    <IODINE_MCG>181.33</IODINE_MCG>
    <MAGNESIUM_MG>.04</MAGNESIUM_MG>
    <ZINC_MG>0</ZINC_MG>
    <SELENIUM_MCG>0</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2008</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>FSR 2008 Accessory Packet C </ITEMTYPE>
    <ITEM>Group Average - FSR 2008 Accessory Packet C </ITEM>
    <WEIGHT>8.07</WEIGHT>
    <CALORIES>33.83</CALORIES>
    <TOTALFAT_G>.03</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>.01</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>0</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>786.64</SODIUM_MG>
    <SODIUM_DV>.33&#37;</SODIUM_DV>
    <POTASSIUM_MG>1.01</POTASSIUM_MG>
    <CARBOHYDRATES_G>6.27</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.02&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.09</DIETARYFIBER_G>
    <DIETARYFIBER_DV>0&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>