<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (RATION?,MENU?,ITEMTYPE?,ITEM?,WEIGHT?,CALORIES?,TOTALFAT_G?,TOTALFAT_DV?,SATURATEDFAT_G?,SATURATEDFAT_DV?,TRANSFAT_G?,CHOLESTEROL_MG?,CHOLESTEROL_DV?,SODIUM_MG?,SODIUM_DV?,POTASSIUM_MG?,CARBOHYDRATES_G?,CARBOHYDRATES_DV?,DIETARYFIBER_G?,DIETARYFIBER_DV?,SUGARS_G?,PROTEIN_G?,VITAMINA_IU?,VITAMINA_DV?,VITAMINC_MG?,VITAMINC_DV?,CALCIUM_MG?,CALCIUM_DV?,IRON_MG?,IRON_DV?,VITAMIND_MCG?,VITAMINE_MG?,VITAMINK_MCG?,THIAMIN_MG?,RIBOFLAVIN_MG?,NIACIN_MG?,VITAMINB6_MG?,FOLICACID_MCG?,VITAMINB12_MCG?,PHOSPHOROUS_MG?,IODINE_MCG?,MAGNESIUM_MG?,ZINC_MG?,SELENIUM_MCG?)+>
  <!ELEMENT RATION (#PCDATA)>
  <!ELEMENT MENU (#PCDATA)>
  <!ELEMENT ITEMTYPE (#PCDATA)>
  <!ELEMENT ITEM (#PCDATA)>
  <!ELEMENT WEIGHT (#PCDATA)>
  <!ELEMENT CALORIES (#PCDATA)>
  <!ELEMENT TOTALFAT_G (#PCDATA)>
  <!ELEMENT TOTALFAT_DV (#PCDATA)>
  <!ELEMENT SATURATEDFAT_G (#PCDATA)>
  <!ELEMENT SATURATEDFAT_DV (#PCDATA)>
  <!ELEMENT TRANSFAT_G (#PCDATA)>
  <!ELEMENT CHOLESTEROL_MG (#PCDATA)>
  <!ELEMENT CHOLESTEROL_DV (#PCDATA)>
  <!ELEMENT SODIUM_MG (#PCDATA)>
  <!ELEMENT SODIUM_DV (#PCDATA)>
  <!ELEMENT POTASSIUM_MG (#PCDATA)>
  <!ELEMENT CARBOHYDRATES_G (#PCDATA)>
  <!ELEMENT CARBOHYDRATES_DV (#PCDATA)>
  <!ELEMENT DIETARYFIBER_G (#PCDATA)>
  <!ELEMENT DIETARYFIBER_DV (#PCDATA)>
  <!ELEMENT SUGARS_G (#PCDATA)>
  <!ELEMENT PROTEIN_G (#PCDATA)>
  <!ELEMENT VITAMINA_IU (#PCDATA)>
  <!ELEMENT VITAMINA_DV (#PCDATA)>
  <!ELEMENT VITAMINC_MG (#PCDATA)>
  <!ELEMENT VITAMINC_DV (#PCDATA)>
  <!ELEMENT CALCIUM_MG (#PCDATA)>
  <!ELEMENT CALCIUM_DV (#PCDATA)>
  <!ELEMENT IRON_MG (#PCDATA)>
  <!ELEMENT IRON_DV (#PCDATA)>
  <!ELEMENT VITAMIND_MCG (#PCDATA)>
  <!ELEMENT VITAMINE_MG (#PCDATA)>
  <!ELEMENT VITAMINK_MCG (#PCDATA)>
  <!ELEMENT THIAMIN_MG (#PCDATA)>
  <!ELEMENT RIBOFLAVIN_MG (#PCDATA)>
  <!ELEMENT NIACIN_MG (#PCDATA)>
  <!ELEMENT VITAMINB6_MG (#PCDATA)>
  <!ELEMENT FOLICACID_MCG (#PCDATA)>
  <!ELEMENT VITAMINB12_MCG (#PCDATA)>
  <!ELEMENT PHOSPHOROUS_MG (#PCDATA)>
  <!ELEMENT IODINE_MCG (#PCDATA)>
  <!ELEMENT MAGNESIUM_MG (#PCDATA)>
  <!ELEMENT ZINC_MG (#PCDATA)>
  <!ELEMENT SELENIUM_MCG (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Entree</ITEMTYPE>
    <ITEM>Sandwich, Shelf Stable, Bacon Cheddar</ITEM>
    <WEIGHT>88</WEIGHT>
    <CALORIES>327.36</CALORIES>
    <TOTALFAT_G>14.52</TOTALFAT_G>
    <TOTALFAT_DV>.22&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>4.95</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.25&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>2.13</TRANSFAT_G>
    <CHOLESTEROL_MG>20</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>687.28</SODIUM_MG>
    <SODIUM_DV>.29&#37;</SODIUM_DV>
    <POTASSIUM_MG>177.76</POTASSIUM_MG>
    <CARBOHYDRATES_G>37.31</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.12&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.86</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.07&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>12.14</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.88</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>68.99</CALCIUM_MG>
    <CALCIUM_DV>.07&#37;</CALCIUM_DV>
    <IRON_MG>2.24</IRON_MG>
    <IRON_DV>.12&#37;</IRON_DV>
    <VITAMINE_MG>.5</VITAMINE_MG>
    <THIAMIN_MG>.29</THIAMIN_MG>
    <RIBOFLAVIN_MG>.33</RIBOFLAVIN_MG>
    <NIACIN_MG>5.27</NIACIN_MG>
    <VITAMINB6_MG>.12</VITAMINB6_MG>
    <FOLICACID_MCG>82.37</FOLICACID_MCG>
    <VITAMINB12_MCG>.18</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>129.36</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>23.23</MAGNESIUM_MG>
    <ZINC_MG>1.37</ZINC_MG>
    <SELENIUM_MCG>18.74</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Entree</ITEMTYPE>
    <ITEM>Sandwich, Shelf Stable, Pepperoni</ITEM>
    <WEIGHT>70</WEIGHT>
    <CALORIES>265.3</CALORIES>
    <TOTALFAT_G>14.63</TOTALFAT_G>
    <TOTALFAT_DV>.23&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>4.84</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.24&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.32</TRANSFAT_G>
    <CHOLESTEROL_MG>20</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>571.9</SODIUM_MG>
    <SODIUM_DV>.24&#37;</SODIUM_DV>
    <POTASSIUM_MG>135.1</POTASSIUM_MG>
    <CARBOHYDRATES_G>25.27</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.08&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.18</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.05&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>9.66</PROTEIN_G>
    <VITAMINA_IU>128.3</VITAMINA_IU>
    <VITAMINA_DV>.03&#37;</VITAMINA_DV>
    <VITAMINC_MG>.7</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>47.95</CALCIUM_MG>
    <CALCIUM_DV>.05&#37;</CALCIUM_DV>
    <IRON_MG>1.42</IRON_MG>
    <IRON_DV>.08&#37;</IRON_DV>
    <VITAMINE_MG>.49</VITAMINE_MG>
    <THIAMIN_MG>.19</THIAMIN_MG>
    <RIBOFLAVIN_MG>.21</RIBOFLAVIN_MG>
    <NIACIN_MG>3.12</NIACIN_MG>
    <VITAMINB6_MG>.11</VITAMINB6_MG>
    <FOLICACID_MCG>48.93</FOLICACID_MCG>
    <VITAMINB12_MCG>.25</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>91</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>17.08</MAGNESIUM_MG>
    <ZINC_MG>1.13</ZINC_MG>
    <SELENIUM_MCG>16.66</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Pretzels, Sticks</ITEM>
    <WEIGHT>28</WEIGHT>
    <CALORIES>103.88</CALORIES>
    <TOTALFAT_G>.39</TOTALFAT_G>
    <TOTALFAT_DV>.01&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>.1</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.01&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>0</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>403.2</SODIUM_MG>
    <SODIUM_DV>.17&#37;</SODIUM_DV>
    <POTASSIUM_MG>50.12</POTASSIUM_MG>
    <CARBOHYDRATES_G>22.26</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.07&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.96</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.04&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>2.8</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.28</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>8.6</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>1.22</IRON_MG>
    <IRON_DV>.07&#37;</IRON_DV>
    <VITAMINE_MG>.05</VITAMINE_MG>
    <THIAMIN_MG>.11</THIAMIN_MG>
    <RIBOFLAVIN_MG>.15</RIBOFLAVIN_MG>
    <NIACIN_MG>1.57</NIACIN_MG>
    <VITAMINB6_MG>.02</VITAMINB6_MG>
    <FOLICACID_MCG>22.79</FOLICACID_MCG>
    <VITAMINB12_MCG>.03</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>34.44</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>7.64</MAGNESIUM_MG>
    <ZINC_MG>.28</ZINC_MG>
    <SELENIUM_MCG>1.43</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Dessert Bar, Peanut Butter</ITEM>
    <WEIGHT>40</WEIGHT>
    <CALORIES>231.6</CALORIES>
    <TOTALFAT_G>17.16</TOTALFAT_G>
    <TOTALFAT_DV>.26&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>6.08</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.3&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.47</TRANSFAT_G>
    <CHOLESTEROL_MG>20.24</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>37.08</SODIUM_MG>
    <SODIUM_DV>.02&#37;</SODIUM_DV>
    <POTASSIUM_MG>242.8</POTASSIUM_MG>
    <CARBOHYDRATES_G>16.12</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.05&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>8.52</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.34&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>6.76</PROTEIN_G>
    <VITAMINA_IU>185.9</VITAMINA_IU>
    <VITAMINA_DV>.04&#37;</VITAMINA_DV>
    <VITAMINC_MG>.4</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>77.6</CALCIUM_MG>
    <CALCIUM_DV>.08&#37;</CALCIUM_DV>
    <IRON_MG>.22</IRON_MG>
    <IRON_DV>.01&#37;</IRON_DV>
    <VITAMIND_MCG>.3</VITAMIND_MCG>
    <VITAMINE_MG>1.62</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.02</THIAMIN_MG>
    <RIBOFLAVIN_MG>.16</RIBOFLAVIN_MG>
    <NIACIN_MG>2.59</NIACIN_MG>
    <VITAMINB6_MG>.05</VITAMINB6_MG>
    <FOLICACID_MCG>13.16</FOLICACID_MCG>
    <VITAMINB12_MCG>.22</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>138.8</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>31.76</MAGNESIUM_MG>
    <ZINC_MG>.75</ZINC_MG>
    <SELENIUM_MCG>3.08</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Beef Snacks, Teriyaki</ITEM>
    <WEIGHT>26</WEIGHT>
    <CALORIES>78.26</CALORIES>
    <TOTALFAT_G>2.94</TOTALFAT_G>
    <TOTALFAT_DV>.05&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.33</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.07&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.13</TRANSFAT_G>
    <CHOLESTEROL_MG>20</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>608.4</SODIUM_MG>
    <SODIUM_DV>.25&#37;</SODIUM_DV>
    <POTASSIUM_MG>167.44</POTASSIUM_MG>
    <CARBOHYDRATES_G>5.51</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.02&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.54</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.02&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>7.8</PROTEIN_G>
    <VITAMINA_IU>26.9</VITAMINA_IU>
    <VITAMINA_DV>.01&#37;</VITAMINA_DV>
    <VITAMINC_MG>.26</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>15.21</CALCIUM_MG>
    <CALCIUM_DV>.02&#37;</CALCIUM_DV>
    <IRON_MG>1.23</IRON_MG>
    <IRON_DV>.07&#37;</IRON_DV>
    <VITAMINE_MG>.26</VITAMINE_MG>
    <THIAMIN_MG>.03</THIAMIN_MG>
    <RIBOFLAVIN_MG>.15</RIBOFLAVIN_MG>
    <NIACIN_MG>1.37</NIACIN_MG>
    <VITAMINB6_MG>.06</VITAMINB6_MG>
    <FOLICACID_MCG>5.82</FOLICACID_MCG>
    <VITAMINB12_MCG>1.54</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>72.28</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>12.58</MAGNESIUM_MG>
    <ZINC_MG>1.31</ZINC_MG>
    <SELENIUM_MCG>6.94</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Beef Snacks, Barbecue</ITEM>
    <WEIGHT>26</WEIGHT>
    <CALORIES>76.7</CALORIES>
    <TOTALFAT_G>2.78</TOTALFAT_G>
    <TOTALFAT_DV>.04&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.17</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.06&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.13</TRANSFAT_G>
    <CHOLESTEROL_MG>20</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.07&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>564.2</SODIUM_MG>
    <SODIUM_DV>.24&#37;</SODIUM_DV>
    <POTASSIUM_MG>173.94</POTASSIUM_MG>
    <CARBOHYDRATES_G>4.91</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.02&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.72</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.03&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>8.61</PROTEIN_G>
    <VITAMINA_IU>131.2</VITAMINA_IU>
    <VITAMINA_DV>.03&#37;</VITAMINA_DV>
    <VITAMINC_MG>.26</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>13.7</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>1.16</IRON_MG>
    <IRON_DV>.06&#37;</IRON_DV>
    <VITAMINE_MG>.33</VITAMINE_MG>
    <THIAMIN_MG>.03</THIAMIN_MG>
    <RIBOFLAVIN_MG>.15</RIBOFLAVIN_MG>
    <NIACIN_MG>1.38</NIACIN_MG>
    <VITAMINB6_MG>.05</VITAMINB6_MG>
    <FOLICACID_MCG>5.36</FOLICACID_MCG>
    <VITAMINB12_MCG>1.53</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>73.06</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>12.4</MAGNESIUM_MG>
    <ZINC_MG>1.29</ZINC_MG>
    <SELENIUM_MCG>6.37</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Filled Bakery, Filled French Toast</ITEM>
    <WEIGHT>99</WEIGHT>
    <CALORIES>322.74</CALORIES>
    <TOTALFAT_G>10.1</TOTALFAT_G>
    <TOTALFAT_DV>.16&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.55</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.18&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.83</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>305.91</SODIUM_MG>
    <SODIUM_DV>.13&#37;</SODIUM_DV>
    <POTASSIUM_MG>76.13</POTASSIUM_MG>
    <CARBOHYDRATES_G>52.27</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.17&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>2</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.08&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>6.83</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.99</VITAMINC_MG>
    <VITAMINC_DV>.02&#37;</VITAMINC_DV>
    <CALCIUM_MG>60.89</CALCIUM_MG>
    <CALCIUM_DV>.06&#37;</CALCIUM_DV>
    <IRON_MG>2.53</IRON_MG>
    <IRON_DV>.14&#37;</IRON_DV>
    <VITAMIND_MCG>0</VITAMIND_MCG>
    <VITAMINE_MG>.62</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.27</THIAMIN_MG>
    <RIBOFLAVIN_MG>.28</RIBOFLAVIN_MG>
    <NIACIN_MG>2.83</NIACIN_MG>
    <VITAMINB6_MG>.06</VITAMINB6_MG>
    <FOLICACID_MCG>67.72</FOLICACID_MCG>
    <VITAMINB12_MCG>.12</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>58.91</PHOSPHOROUS_MG>
    <IODINE_MCG>.85</IODINE_MCG>
    <MAGNESIUM_MG>16.04</MAGNESIUM_MG>
    <ZINC_MG>.7</ZINC_MG>
    <SELENIUM_MCG>16.14</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Nut and Fruit Mix, Sunflower Kernels and Infused Fruit</ITEM>
    <WEIGHT>56</WEIGHT>
    <CALORIES>314.72</CALORIES>
    <TOTALFAT_G>21.17</TOTALFAT_G>
    <TOTALFAT_DV>.33&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>3.18</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.16&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.03</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>5.6</SODIUM_MG>
    <SODIUM_DV>0&#37;</SODIUM_DV>
    <POTASSIUM_MG>339.92</POTASSIUM_MG>
    <CARBOHYDRATES_G>18.42</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.06&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>10.58</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.42&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>12.6</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.56</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>43.12</CALCIUM_MG>
    <CALCIUM_DV>.04&#37;</CALCIUM_DV>
    <IRON_MG>1.07</IRON_MG>
    <IRON_DV>.06&#37;</IRON_DV>
    <VITAMINE_MG>3.65</VITAMINE_MG>
    <THIAMIN_MG>.08</THIAMIN_MG>
    <RIBOFLAVIN_MG>.09</RIBOFLAVIN_MG>
    <NIACIN_MG>5.88</NIACIN_MG>
    <VITAMINB6_MG>.31</VITAMINB6_MG>
    <FOLICACID_MCG>47.66</FOLICACID_MCG>
    <VITAMINB12_MCG>.07</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>190.96</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>91.84</MAGNESIUM_MG>
    <ZINC_MG>1.57</ZINC_MG>
    <SELENIUM_MCG>4.65</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>First Strike Bar, Mini, Chocolate</ITEM>
    <WEIGHT>35</WEIGHT>
    <CALORIES>149.8</CALORIES>
    <TOTALFAT_G>5.08</TOTALFAT_G>
    <TOTALFAT_DV>.08&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.66</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.08&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.01</TRANSFAT_G>
    <CHOLESTEROL_MG>2.67</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.01&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>18.1</SODIUM_MG>
    <SODIUM_DV>.01&#37;</SODIUM_DV>
    <POTASSIUM_MG>111.3</POTASSIUM_MG>
    <CARBOHYDRATES_G>24.26</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.08&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.26</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.05&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>2.03</PROTEIN_G>
    <VITAMINA_IU>43.9</VITAMINA_IU>
    <VITAMINA_DV>.01&#37;</VITAMINA_DV>
    <VITAMINC_MG>13.16</VITAMINC_MG>
    <VITAMINC_DV>.22&#37;</VITAMINC_DV>
    <CALCIUM_MG>21.39</CALCIUM_MG>
    <CALCIUM_DV>.02&#37;</CALCIUM_DV>
    <IRON_MG>1.7</IRON_MG>
    <IRON_DV>.09&#37;</IRON_DV>
    <VITAMIND_MCG>1.1</VITAMIND_MCG>
    <VITAMINE_MG>8.56</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.27</THIAMIN_MG>
    <RIBOFLAVIN_MG>.32</RIBOFLAVIN_MG>
    <NIACIN_MG>2.98</NIACIN_MG>
    <VITAMINB6_MG>.31</VITAMINB6_MG>
    <FOLICACID_MCG>135.8</FOLICACID_MCG>
    <VITAMINB12_MCG>1.02</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>13.39</PHOSPHOROUS_MG>
    <IODINE_MCG>0</IODINE_MCG>
    <MAGNESIUM_MG>21.56</MAGNESIUM_MG>
    <ZINC_MG>1.83</ZINC_MG>
    <SELENIUM_MCG>1.05</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Bread/Crax</ITEMTYPE>
    <ITEM>Snack Bread, Wheat</ITEM>
    <WEIGHT>57</WEIGHT>
    <CALORIES>201.78</CALORIES>
    <TOTALFAT_G>6.21</TOTALFAT_G>
    <TOTALFAT_DV>.1&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.53</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.08&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.57</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>369.36</SODIUM_MG>
    <SODIUM_DV>.15&#37;</SODIUM_DV>
    <POTASSIUM_MG>80.94</POTASSIUM_MG>
    <CARBOHYDRATES_G>32.43</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.11&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.82</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.07&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>4.73</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>.57</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>172.71</CALCIUM_MG>
    <CALCIUM_DV>.17&#37;</CALCIUM_DV>
    <IRON_MG>1.98</IRON_MG>
    <IRON_DV>.11&#37;</IRON_DV>
    <VITAMIND_MCG>0</VITAMIND_MCG>
    <VITAMINE_MG>.26</VITAMINE_MG>
    <THIAMIN_MG>.25</THIAMIN_MG>
    <RIBOFLAVIN_MG>.2</RIBOFLAVIN_MG>
    <NIACIN_MG>2.6</NIACIN_MG>
    <VITAMINB6_MG>.05</VITAMINB6_MG>
    <FOLICACID_MCG>58.14</FOLICACID_MCG>
    <VITAMINB12_MCG>.07</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>148.2</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>18.87</MAGNESIUM_MG>
    <ZINC_MG>.43</ZINC_MG>
    <SELENIUM_MCG>19.67</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Spread</ITEMTYPE>
    <ITEM>Cheese Spread, Cheddar with Jalapeno Peppers and Vitamin D</ITEM>
    <WEIGHT>42.75</WEIGHT>
    <CALORIES>160.51</CALORIES>
    <TOTALFAT_G>16.61</TOTALFAT_G>
    <TOTALFAT_DV>.26&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>8.48</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.42&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.74</TRANSFAT_G>
    <CHOLESTEROL_MG>45</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.15&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>607.05</SODIUM_MG>
    <SODIUM_DV>.25&#37;</SODIUM_DV>
    <POTASSIUM_MG>29.6</POTASSIUM_MG>
    <CARBOHYDRATES_G>4.41</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.37</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.01&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>5.22</PROTEIN_G>
    <VITAMINA_IU>3101.85</VITAMINA_IU>
    <VITAMINA_DV>.62&#37;</VITAMINA_DV>
    <VITAMINC_MG>.22</VITAMINC_MG>
    <VITAMINC_DV>0&#37;</VITAMINC_DV>
    <CALCIUM_MG>160.77</CALCIUM_MG>
    <CALCIUM_DV>.16&#37;</CALCIUM_DV>
    <IRON_MG>.09</IRON_MG>
    <IRON_DV>.01&#37;</IRON_DV>
    <VITAMIND_MCG>2.7</VITAMIND_MCG>
    <VITAMINE_MG>1.24</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>.67</THIAMIN_MG>
    <RIBOFLAVIN_MG>.12</RIBOFLAVIN_MG>
    <NIACIN_MG>.04</NIACIN_MG>
    <VITAMINB6_MG>.79</VITAMINB6_MG>
    <FOLICACID_MCG>4.07</FOLICACID_MCG>
    <VITAMINB12_MCG>.1</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>268.28</PHOSPHOROUS_MG>
    <IODINE_MCG>0</IODINE_MCG>
    <MAGNESIUM_MG>6.54</MAGNESIUM_MG>
    <ZINC_MG>.89</ZINC_MG>
    <SELENIUM_MCG>6.37</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Candy</ITEMTYPE>
    <ITEM>Caffeinated Gum, Cinnamon</ITEM>
    <WEIGHT>12.5</WEIGHT>
    <CALORIES>50</CALORIES>
    <CARBOHYDRATES_G>10</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.03&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
    <VITAMINA_DV> </VITAMINA_DV>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Beverage</ITEMTYPE>
    <ITEM>Chocolate Protein Drink</ITEM>
    <WEIGHT>70</WEIGHT>
    <CALORIES>271.6</CALORIES>
    <TOTALFAT_G>1.69</TOTALFAT_G>
    <TOTALFAT_DV>.03&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.05&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.02</TRANSFAT_G>
    <CHOLESTEROL_MG>5.6</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.02&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>230.3</SODIUM_MG>
    <SODIUM_DV>.1&#37;</SODIUM_DV>
    <CARBOHYDRATES_G>50.52</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.17&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>5.18</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.21&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>13.59</PROTEIN_G>
    <VITAMINA_IU>1428</VITAMINA_IU>
    <VITAMINA_DV>.29&#37;</VITAMINA_DV>
    <VITAMINC_MG>25.69</VITAMINC_MG>
    <VITAMINC_DV>.43&#37;</VITAMINC_DV>
    <CALCIUM_MG>270.9</CALCIUM_MG>
    <CALCIUM_DV>.27&#37;</CALCIUM_DV>
    <IRON_MG>12.32</IRON_MG>
    <IRON_DV>.68&#37;</IRON_DV>
    <VITAMIND_MCG>4.8</VITAMIND_MCG>
    <THIAMIN_MG>.58</THIAMIN_MG>
    <RIBOFLAVIN_MG>.64</RIBOFLAVIN_MG>
    <NIACIN_MG>11.76</NIACIN_MG>
    <VITAMINB6_MG>.88</VITAMINB6_MG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Beverage</ITEMTYPE>
    <ITEM>Beverage Base, Ergo, Formulation E</ITEM>
    <WEIGHT>47</WEIGHT>
    <CALORIES>171.08</CALORIES>
    <TOTALFAT_G>.05</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>0</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>0</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>87.89</SODIUM_MG>
    <SODIUM_DV>.04&#37;</SODIUM_DV>
    <POTASSIUM_MG>4.7</POTASSIUM_MG>
    <CARBOHYDRATES_G>42.54</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.14&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.47</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.02&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.28</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>37.08</VITAMINC_MG>
    <VITAMINC_DV>.62&#37;</VITAMINC_DV>
    <CALCIUM_MG>6.82</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>.12</IRON_MG>
    <IRON_DV>.01&#37;</IRON_DV>
    <VITAMINE_MG>.21</VITAMINE_MG>
    <THIAMIN_MG>.01</THIAMIN_MG>
    <RIBOFLAVIN_MG>.01</RIBOFLAVIN_MG>
    <NIACIN_MG>.01</NIACIN_MG>
    <VITAMINB6_MG>0</VITAMINB6_MG>
    <FOLICACID_MCG>2.82</FOLICACID_MCG>
    <VITAMINB12_MCG>.06</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>2.87</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>2.39</MAGNESIUM_MG>
    <ZINC_MG>.04</ZINC_MG>
    <SELENIUM_MCG>1.41</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Fruit</ITEMTYPE>
    <ITEM>Fruits, Wet Pack, Applesauce, Carbohydrate Enhanced, Cinnamon</ITEM>
    <WEIGHT>125</WEIGHT>
    <CALORIES>127.5</CALORIES>
    <TOTALFAT_G>.08</TOTALFAT_G>
    <TOTALFAT_DV>0&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>.03</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>0</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>12.5</SODIUM_MG>
    <SODIUM_DV>.01&#37;</SODIUM_DV>
    <CARBOHYDRATES_G>31.46</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.1&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>2.13</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.09&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>.19</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>1.12</VITAMINC_MG>
    <VITAMINC_DV>.02&#37;</VITAMINC_DV>
    <CALCIUM_MG>13.75</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>0</IRON_MG>
    <IRON_DV>0&#37;</IRON_DV>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Accessory Pkt</ITEMTYPE>
    <ITEM>Chewing Gum, Xylitol</ITEM>
    <WEIGHT>3.2</WEIGHT>
    <CARBOHYDRATES_G>2</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <SUGARS_G>0</SUGARS_G>
    <VITAMINA_DV> </VITAMINA_DV>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 1</MENU>
    <ITEMTYPE>Total</ITEMTYPE>
    <WEIGHT>825.45</WEIGHT>
    <CALORIES>2852.83</CALORIES>
    <TOTALFAT_G>113.41</TOTALFAT_G>
    <TOTALFAT_DV>0</TOTALFAT_DV>
    <SATURATEDFAT_G>37.9</SATURATEDFAT_G>
    <SATURATEDFAT_DV>0</SATURATEDFAT_DV>
    <TRANSFAT_G>10.38</TRANSFAT_G>
    <CHOLESTEROL_MG>153.51</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0</CHOLESTEROL_DV>
    <SODIUM_MG>4508.77</SODIUM_MG>
    <SODIUM_DV>0</SODIUM_DV>
    <POTASSIUM_MG>1589.75</POTASSIUM_MG>
    <CARBOHYDRATES_G>379.69</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>0</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>37.59</DIETARYFIBER_G>
    <DIETARYFIBER_DV>0</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>93.24</PROTEIN_G>
    <VITAMINA_IU>5046.05</VITAMINA_IU>
    <VITAMINA_DV>0</VITAMINA_DV>
    <VITAMINC_MG>82.17</VITAMINC_MG>
    <VITAMINC_DV>0</VITAMINC_DV>
    <CALCIUM_MG>982.4</CALCIUM_MG>
    <CALCIUM_DV>0</CALCIUM_DV>
    <IRON_MG>27.3</IRON_MG>
    <IRON_DV>0</IRON_DV>
    <VITAMIND_MCG>8.9</VITAMIND_MCG>
    <VITAMINE_MG>17.79</VITAMINE_MG>
    <VITAMINK_MCG>0</VITAMINK_MCG>
    <THIAMIN_MG>2.8</THIAMIN_MG>
    <RIBOFLAVIN_MG>2.81</RIBOFLAVIN_MG>
    <NIACIN_MG>41.4</NIACIN_MG>
    <VITAMINB6_MG>2.81</VITAMINB6_MG>
    <FOLICACID_MCG>494.64</FOLICACID_MCG>
    <VITAMINB12_MCG>5.19</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>1221.55</PHOSPHOROUS_MG>
    <IODINE_MCG>.85</IODINE_MCG>
    <MAGNESIUM_MG>261.93</MAGNESIUM_MG>
    <ZINC_MG>11.59</ZINC_MG>
    <SELENIUM_MCG>102.51</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 2</MENU>
    <ITEMTYPE>Entree</ITEMTYPE>
    <ITEM>Sandwich, Shelf Stable, Italian Style</ITEM>
    <WEIGHT>100</WEIGHT>
    <CALORIES>319</CALORIES>
    <TOTALFAT_G>13.8</TOTALFAT_G>
    <TOTALFAT_DV>.21&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>4.25</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.21&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>1.91</TRANSFAT_G>
    <CHOLESTEROL_MG>15</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.05&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>727</SODIUM_MG>
    <SODIUM_DV>.3&#37;</SODIUM_DV>
    <POTASSIUM_MG>244</POTASSIUM_MG>
    <CARBOHYDRATES_G>38.9</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.13&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>2.11</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.08&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>11.3</PROTEIN_G>
    <VITAMINA_IU>59</VITAMINA_IU>
    <VITAMINA_DV>.01&#37;</VITAMINA_DV>
    <VITAMINC_MG>1</VITAMINC_MG>
    <VITAMINC_DV>.02&#37;</VITAMINC_DV>
    <CALCIUM_MG>88.4</CALCIUM_MG>
    <CALCIUM_DV>.09&#37;</CALCIUM_DV>
    <IRON_MG>2.14</IRON_MG>
    <IRON_DV>.12&#37;</IRON_DV>
    <VITAMINE_MG>1.06</VITAMINE_MG>
    <THIAMIN_MG>.21</THIAMIN_MG>
    <RIBOFLAVIN_MG>.23</RIBOFLAVIN_MG>
    <NIACIN_MG>3.51</NIACIN_MG>
    <VITAMINB6_MG>.14</VITAMINB6_MG>
    <FOLICACID_MCG>51.9</FOLICACID_MCG>
    <VITAMINB12_MCG>.2</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>121</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>26.3</MAGNESIUM_MG>
    <ZINC_MG>1.35</ZINC_MG>
    <SELENIUM_MCG>20.4</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 2</MENU>
    <ITEMTYPE>Entree</ITEMTYPE>
    <ITEM>Chicken Chunks, White</ITEM>
    <WEIGHT>196</WEIGHT>
    <CALORIES>192.67</CALORIES>
    <TOTALFAT_G>1.81</TOTALFAT_G>
    <TOTALFAT_DV>.03&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>.51</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.03&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.01</TRANSFAT_G>
    <CHOLESTEROL_MG>87.5</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>.29&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>740.88</SODIUM_MG>
    <SODIUM_DV>.31&#37;</SODIUM_DV>
    <POTASSIUM_MG>591.92</POTASSIUM_MG>
    <CARBOHYDRATES_G>1.96</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.01&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>1.96</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.08&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>42.92</PROTEIN_G>
    <VITAMINA_IU>0</VITAMINA_IU>
    <VITAMINA_DV>0&#37;</VITAMINA_DV>
    <VITAMINC_MG>1.96</VITAMINC_MG>
    <VITAMINC_DV>.03&#37;</VITAMINC_DV>
    <CALCIUM_MG>9.9</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>.69</IRON_MG>
    <IRON_DV>.04&#37;</IRON_DV>
    <VITAMINE_MG>1.12</VITAMINE_MG>
    <THIAMIN_MG>.03</THIAMIN_MG>
    <RIBOFLAVIN_MG>.29</RIBOFLAVIN_MG>
    <NIACIN_MG>22.74</NIACIN_MG>
    <VITAMINB6_MG>.33</VITAMINB6_MG>
    <FOLICACID_MCG>42.73</FOLICACID_MCG>
    <VITAMINB12_MCG>.24</VITAMINB12_MCG>
    <PHOSPHOROUS_MG>631.12</PHOSPHOROUS_MG>
    <MAGNESIUM_MG>49.98</MAGNESIUM_MG>
    <ZINC_MG>1.35</ZINC_MG>
    <SELENIUM_MCG>40.96</SELENIUM_MCG>
  </DATA_RECORD>
  <DATA_RECORD>
    <RATION>FSR2012</RATION>
    <MENU>MENU 2</MENU>
    <ITEMTYPE>Snack</ITEMTYPE>
    <ITEM>Toaster Pastry, Frosted Brown Sugar Cinnamon</ITEM>
    <WEIGHT>51</WEIGHT>
    <CALORIES>204.09</CALORIES>
    <TOTALFAT_G>6.06</TOTALFAT_G>
    <TOTALFAT_DV>.09&#37;</TOTALFAT_DV>
    <SATURATEDFAT_G>1.72</SATURATEDFAT_G>
    <SATURATEDFAT_DV>.09&#37;</SATURATEDFAT_DV>
    <TRANSFAT_G>.66</TRANSFAT_G>
    <CHOLESTEROL_MG>0</CHOLESTEROL_MG>
    <CHOLESTEROL_DV>0&#37;</CHOLESTEROL_DV>
    <SODIUM_MG>164.09</SODIUM_MG>
    <SODIUM_DV>.07&#37;</SODIUM_DV>
    <POTASSIUM_MG>48.65</POTASSIUM_MG>
    <CARBOHYDRATES_G>35.31</CARBOHYDRATES_G>
    <CARBOHYDRATES_DV>.12&#37;</CARBOHYDRATES_DV>
    <DIETARYFIBER_G>.94</DIETARYFIBER_G>
    <DIETARYFIBER_DV>.04&#37;</DIETARYFIBER_DV>
    <SUGARS_G>0</SUGARS_G>
    <PROTEIN_G>2.45</PROTEIN_G>
    <VITAMINA_IU>536.7</VITAMINA_IU>
    <VITAMINA_DV>.11&#37;</VITAMINA_DV>
    <VITAMINC_MG>.51</VITAMINC_MG>
    <VITAMINC_DV>.01&#37;</VITAMINC_DV>
    <CALCIUM_MG>12.73</CALCIUM_MG>
    <CALCIUM_DV>.01&#37;</CALCIUM_DV>
    <IRON_MG>1.88</IRON_MG>
    <IRON_DV>.1&#37;</IRON_DV>